### ISSUE TITLE
Questions about featureset

### ISSUE THREAD

**Issue by NotNite** [HexaEngine/Hexa.NET.KittyUI#3]
Hi! I was redirected here from https://github.com/HexaEngine/Hexa.NET.ImGui/issues/22 and I have some questions about using this in [my app](https://github.com/NotNite/ImSky). I took a very brief look over the repository so I probably missed a lot (sorry lol). There are a few features I'd need from this for it to be feasible:

- Either being able to customize the config system path, or being able to skip it all together
  - From a brief look it looks like this has its own config system which just writes to `config.json` in the current directory. I currently have my own config system and it'd be nice to just save the window pos/size there and keep my existing code/format
  - The ImGui app .ini also comes to mind for something to save
- Configurable fonts, and the option to keep the default font (I love the default Proggy Clean font, but people often need other fonts for accessibility reasons)
- Customizable app icon (not a huge requirement)
- Image rendering
  - I currently have a system that tracks the usage of images and automatically disposes old images, so I can write very lazy UI code and scroll through feeds without any issue

Besides these blockers for integration of my existing project, this seems like an amazing project and I will 100% be using it in the future. Do these exist/can they exist/are there workarounds for these? Thanks!

**Comment by JunaMeinhold** [comment]
The config thing is orphan code and originally from my game engine, I will probably remove it in the future, because at the moment it just sits there and does nothing. 

Font wise it works like this
```cs
appBuilder.AddFont(fontBuilder =>
{
    fontBuilder.AddFontFromFileTTF("yourfont.ttf", 16);
});
```

For app icon see, SDL2 automatically uses that, works on linux too. (i think)
![image](https://github.com/user-attachments/assets/c6cc0631-2d44-4c4f-b36a-18bf8dc7b2ba)

Image wise, I'm working on a abstraction layer for that currently there is only Image.LoadFromFile, it supports many file formats all WIC (on linux just png and jpg) formats DDS TGA HDR (all platforms).

**Comment by NotNite** [comment]
Noted, thank you! I would be interested in the image stuff once it's done (+ a bump of all the dependencies, since right now it uses a quite old version of the ImGui package on NuGet and I need stuff like FreeType).

**Comment by JunaMeinhold** [comment]
Done, I updated everything, took a bit longer (had to update the dependencies too). And thanks for your donation. I'm going to sleep now, it's 2am at my place.

**Comment by NotNite** [comment]
Seem to be running into an issue starting an app on Windows (.NET 8, v1.0.2):

```cs
using Hexa.NET.ImGui;
using Hexa.NET.KittyUI;

new AppBuilder()
    .SetTitle("Meow :3")
    .AddWindow("Meow", () => { ImGui.Text(":3"); })
    .Run();
```

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Silk.NET.DXGI.DXGIOutput6VtblExtensions.GetDesc1(ComPtr`1 thisVtbl, OutputDesc1* pDesc)
   at Hexa.NET.KittyUI.D3D11.D3D11Adapter.AutoChooseSwapChainFormat(ComPtr`1 device, ComPtr`1 output)
   at Hexa.NET.KittyUI.D3D11.D3D11Adapter.CreateSwapChainForWindow(CoreWindow window)
   at Hexa.NET.KittyUI.Windows.Window.Initialize(AppBuilder appBuilder)
   at Hexa.NET.KittyUI.Application.RegisterWindow(IRenderWindow window)
   at Hexa.NET.KittyUI.Windows.CoreWindow.Show()
   at Hexa.NET.KittyUI.Application.Run(IRenderWindow mainWindow, AppBuilder builder)
   at Hexa.NET.KittyUI.AppBuilder.Run()
   at Program.<Main>$(String[] args) in D:\code\csharp\KittyTest\KittyTest\Program.cs:line 4
```

**Comment by JunaMeinhold** [comment]
Fixed it hopefully :3, if not then set the graphics backend to OpenGL with
```cs
appBuilder.SetGraphicsBackend(Hexa.NET.KittyUI.Windows.GraphicsBackend.OpenGL)
```
![image](https://github.com/user-attachments/assets/20c96224-9fa2-4040-b864-acc286e9e6a7)

**Comment by JunaMeinhold** [comment]
I added a neat way to load images from the web, it caches the image onto the disk to accelerate loading times, it's also fully thread-safe. 
![image](https://github.com/user-attachments/assets/49160249-65c2-401b-a633-aec6010d71f9)

**Comment by NotNite** [comment]
Thank you! I forgot to post here when I ran into an issue - is it possible to disable the custom styles? I would prefer to use the default ImGui styling and apply my own, but the library seems to tweak the styles/colors by default.

**Comment by JunaMeinhold** [comment]
you can also style everything directly with Ctrl+Shift+D in your app, in this little debugging tool
![image](https://github.com/user-attachments/assets/3dd4eecd-27cc-49cd-bccf-265439023fee)

**Comment by JunaMeinhold** [comment]
Oh and you can also make your own titlebars, if the custom icon method doesn't work. (tested on win10 win11, linux x11/wayland kde plasma)
![image](https://github.com/user-attachments/assets/9d644b30-1571-4843-bedd-2ec1957b8371)
