### ISSUE TITLE
TestApp throws exception when LoadTexure button is pressed (MacOS)

### ISSUE THREAD

**Issue by bparvanov** [HexaEngine/Hexa.NET.KittyUI#6]
Can't find stbimage.dylib.. 

System.TypeInitializationException: The type initializer for 'Hexa.NET.StbImage.StbImage' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'stbimage.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(stbimage.dylib, 0x0001): tried: 'stbimage.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSstbimage.dylib' (no such file), '/usr/lib/stbimage.dylib' (no such file, not in dyld cache), 'stbimage.dylib' (no such file), '/usr/local/lib/stbimage.dylib' (no such file), '/usr/lib/stbimage.dylib' (no such file, not in dyld cache)

   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at HexaGen.Runtime.LibraryLoader.LoadLibrary(LibraryNameCallback libraryNameCallback, LibraryExtensionCallback libraryExtensionCallback)
   at Hexa.NET.StbImage.StbImage.InitApi()
   at Hexa.NET.StbImage.StbImage..cctor()
   --- End of inner exception stack trace ---
   at Hexa.NET.StbImage.StbImage.Is16Bit(String filename)
   at Hexa.NET.KittyUI.Graphics.Imaging.TextureLoader.HandleStbImageFile(String filename, ScratchImage& image) in /Users/borislav/Projects/Hexa.NET.KittyUI/Hexa.NET.KittyUI/Graphics/Imaging/TextureLoader.cs:line 88
   at Hexa.NET.KittyUI.Graphics.Imaging.TextureLoader.LoadFormFile(String filename) in /Users/borislav/Projects/Hexa.NET.KittyUI/Hexa.NET.KittyUI/Graphics/Imaging/TextureLoader.cs:line 72
   at Hexa.NET.KittyUI.Graphics.Image2D.LoadFromFile(String path) in /Users/borislav/Projects/Hexa.NET.KittyUI/Hexa.NET.KittyUI/Graphics/Image2D.cs:line 36
   at TestApp.MainWindow.<>c__DisplayClass5_0.<LoadTexture>b__0() in /Users/borislav/Projects/Hexa.NET.KittyUI/TestApp/Program.cs:line 64
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by JunaMeinhold** [comment]
That's just a typo in the GetLibraryName method from StbImage

**Comment by JunaMeinhold** [comment]
Will probably crash now at the libDirectXTex.dylib, i didn't check for rpath on that lib

**Comment by JunaMeinhold** [comment]
okay it looks fine
![image](https://github.com/user-attachments/assets/7d781e6e-c2d9-4d20-b4e4-e660f7b43dfa)

**Comment by bparvanov** [comment]
Now it crashes on GL.CreateBuffers in OpenGLTextureTask.cs...

The editor says the function is supported in OpenGL 4.5-4.6, but as far as I know the latest version on Macs is 4.1.. 
I guess that is the reason for the crash

<img width="1440" alt="Screenshot 2024-11-06 at 13 53 01" src="https://github.com/user-attachments/assets/66bb1e00-70d1-42c4-b987-95bc01ab28db">

**Comment by bparvanov** [comment]
I found this:

https://stackoverflow.com/a/66761752
"Some of these layering options can be stacked. For instance, Zink and DXVK can run on top of MoltenVK, providing OpenGL-over-Vulkan-over-Metal and DX-over-Vulkan-over-Metal functionality."

but I am not sure how helpful it is

**Comment by JunaMeinhold** [comment]
I added a alternative path for opengl versions that don't support PBOs

**Comment by bparvanov** [comment]
The texture now shows up
